Rankingwo
ShunDeveloper/prtimes_htmlcss pull request #11
Opened 2023-05-11 03:19 UTC by ShunDeveloper

## Issue
#5 

## 行ったこと
- divで6カラム分のGridをCSSを用いて作成(上下中央揃え)
- Gridの中に写真・記事タイトル・投稿時間・時計アイコン・時間情報・会社情報・PV情報・順位を追加
- CSSの記述

## Picture
<img width="1728" alt="スクリーンショット 2023-05-11 12 17 20" src="https://github.com/ShunDeveloper/prtimes_htmlcss/assets/84004458/f7013029-19e4-4226-8956-936292a560be">

2023-05-11 07:57 UTC, TepyThai reviewed
細かく書いていますが、わからないところがあれば声かけてください 👍

2023-05-11 07:57 UTC, TepyThai commented on index.html
> +      <div class="item ranking__item">
こちらは `ranking__card`だけで良いかと。`item`でもいいですけど、`card`の方が分かりやすいと思いますね。

2023-05-11 07:57 UTC, TepyThai commented on index.html
> +      </div>
```suggestion
        <img class="card__image"  src="img/ranking/ranking_img1.png" alt="ランキング1位"/>
        <div class="card__overlay">
          <p class="card__overlay__text">1</p>
        </div>
        <h2 class="card__title"> 【新型コロナ感染者数マップ】緊急事態宣言発令状況やを東京都市区町村別... </h2>
        <div class="card__time">
          <img class="card__time__icon" src="img/global/clock.png" alt="time"/>
          <span class="card__time__text">2時間前</span>
        </div>
        <p class="card__company-name">いちから株式会社</p>
        <p class="card__view-count">PV 00,000 / UU 00,000</p>
      </div>
```

2023-05-11 07:57 UTC, TepyThai commented on index.html
> +      </div>
- `box`より`time`の方が意図と近いかと思います。
- `companyname`->`company-name`の方がよみやすいですね。
- `pvuu`も少し分かりづらいので、`view-count｀とかの方が良いと思います。
- `h3`->`h2`
- `<span class="card__time__text">2時間前</span>`：CSSでinlineにしているみたいですが、inline要素の`span`を推奨です。imgタグのスタイルで`inline`にする必要がありますが…

2023-05-11 07:57 UTC, TepyThai commented on index.html
> +      </div>
こちらも同じ

2023-05-11 07:57 UTC, TepyThai commented on index.html
> +        <img class="item__image"  src="img/ranking/ranking_img1.png" alt="ランキング1位"/>
画像はできれば`width`と`height`を指定した方が良くて、必要な場合、`object-fit`なども使った方が良いです。

2023-05-11 07:57 UTC, TepyThai commented on index.html
> +        <img class="item__image"  src="img/ranking/ranking_img1.png" alt="ランキング1位"/>
![Screenshot 2023-05-11 at 16 24 46](https://github.com/ShunDeveloper/prtimes_htmlcss/assets/6161814/6b46b165-f807-4e7a-9c18-1750b8d2b5a2)
また、画面が小さくなると、ちゃんとresponsiveで対応するなら、別のlayoutとかにするのは良いですが、今回は`width`を指定するだけで大丈夫です。`height`は`auto`でOKです。

2023-05-11 07:57 UTC, TepyThai commented on styles/ranking.css
> +  line-height: 18px;
`font-size`,`line-height`はできれば、textのところに設定したい方が良いです。

2023-05-11 07:57 UTC, TepyThai commented on styles/ranking.css
> +  padding-inline: 10px;
`card`の画像は全幅になっているので、`padding`は`card`全体ではなく、`title`の下の部分だけに入れた方が良い

2023-05-11 07:57 UTC, TepyThai commented on styles/ranking.css
> +  left: 0%;
`%`は間違っていないですが、あまりみないですね。`top`,`left`とかは大体 `top: 0`だけですね。

2023-05-11 07:57 UTC, TepyThai commented on styles/ranking.css
> +  /* Additional styles for the overlay */
いらなかったら消して欲しいです

2023-05-11 07:57 UTC, TepyThai commented on styles/ranking.css
> +  font-size: 17px;
`letter-spacing`で`italic`テキストが中央に見えるというhackもあるみたいですね。先程、PR TIMES toppageから検証してみました笑
```suggestion
  font-size: 17px;
  letter-spacing: 3px;
  line-height: 25px;
```

2023-05-11 07:57 UTC, TepyThai commented on index.html
> +      </div>
あとは card__timeはflexboxで中央揃いができる
```
.card__time {
    display: flex;
  align-items: center;
  justify-content: flex-start;
  gap: 5px;
  font-size: 12px;
  line-height: 1;
}
```

2023-05-11 07:57 UTC, TepyThai commented on styles/ranking.css
> +}
```suggestion
```
いらなくなります

2023-05-11 08:38 UTC, ShunDeveloper commented on index.html
> +      <div class="item ranking__item">
以下で修正を行いました！
- [commit](https://github.com/ShunDeveloper/prtimes_htmlcss/pull/11/commits/ca3fd7d3c1fe03126caca19ce67cc515d1888c20)
- [commit2](https://github.com/ShunDeveloper/prtimes_htmlcss/pull/11#:~:text=%E7%A7%BB%E6%A4%8D%E3%81%97%E3%81%BE%E3%81%97%E3%81%9F-,b67281e,-Merge%20state)

2023-05-11 09:08 UTC, shunsock commented on index.html
> +      </div>
[こちらのcommit](https://github.com/ShunDeveloper/prtimes_htmlcss/pull/11/commits/47c12287858cce6905421ad32a3612b9ff8b8a46)で修正をいたしました.

2023-05-11 09:09 UTC, ShunDeveloper commented on index.html
> +      </div>
[こちらのcommit](https://github.com/ShunDeveloper/prtimes_htmlcss/pull/11/commits/47c12287858cce6905421ad32a3612b9ff8b8a46)で修正をいたしました.

2023-05-11 09:35 UTC, ShunDeveloper commented on index.html
> +        <img class="item__image"  src="img/ranking/ranking_img1.png" alt="ランキング1位"/>
[こちらのcommit](https://github.com/ShunDeveloper/prtimes_htmlcss/pull/11/commits/b99e12a3a62e9b6ba695d08cab1ac316aaa4636e)で修正いたしました.

2023-05-11 09:35 UTC, shunsock commented on styles/ranking.css
> +  line-height: 18px;
[こちらのcommit](https://github.com/ShunDeveloper/prtimes_htmlcss/pull/11/commits/b99e12a3a62e9b6ba695d08cab1ac316aaa4636e)で修正いたしました.

2023-05-11 09:42 UTC, ShunDeveloper commented on styles/ranking.css
> +  padding-inline: 10px;
- paddingをtitleに入れるとすると`card__time`などの要素もpaddingを入れる必要がありそうですが, そちらも含めて対応した方が良いでしょうか?
<img width="295" alt="スクリーンショット 2023-05-11 18 40 46" src="https://github.com/ShunDeveloper/prtimes_htmlcss/assets/84004458/862f81dc-5590-4dde-ae22-870eed4a007c">

2023-05-11 09:55 UTC, ShunDeveloper commented on styles/ranking.css
> +  /* Additional styles for the overlay */
[こちら](https://github.com/ShunDeveloper/prtimes_htmlcss/pull/11/commits/ce26a6dc05156f9d9be63085ac72c8ab802a0418)で`/* Additional styles for the overlay */`を削除しました.
他の部分はrankを表示するために使っているので消せないです.

2023-05-11 09:58 UTC, ShunDeveloper commented on styles/ranking.css
> +}
[こちらのcommit](https://github.com/ShunDeveloper/prtimes_htmlcss/pull/11/commits/b99e12a3a62e9b6ba695d08cab1ac316aaa4636e)で対応しました.

2023-05-12 01:06 UTC, ShunDeveloper commented on styles/ranking.css
> +  font-size: 17px;
なるほど, 私の書いたコード上でも上手く動くことが確認できたのでcommitします！

2023-05-12 01:08 UTC, ShunDeveloper commented on styles/ranking.css
> +  font-size: 17px;
[こちらのcommit](https://github.com/ShunDeveloper/prtimes_htmlcss/pull/11/commits/bd8c52f2570ef4c6bda94df32a86e922b052b4c6)で修正しました

2023-05-12 02:18 UTC, ShunDeveloper commented
修正が終わりましたので再度スクリーンショットを掲載します.
<img width="1728" alt="スクリーンショット 2023-05-12 11 17 53" src="https://github.com/ShunDeveloper/prtimes_htmlcss/assets/84004458/3041afbd-bba4-4548-9b77-ecb47885b999">

2023-05-12 02:41 UTC, TepyThai requested changes
@ShunDeveloper conflict解消お疲れ様です。
以下の修正はgithubで直接にできるので、やってみて欲しいです👍

2023-05-12 02:41 UTC, TepyThai commented on styles/ranking.css
> +  line-height: 18px;
18/12=1.5
```suggestion
  line-height: 1.5;
```

2023-05-12 02:41 UTC, TepyThai commented on styles/ranking.css
> +  line-height: 18px;
```suggestion
  line-height: 1.5;
```

2023-05-12 03:08 UTC, ShunDeveloper commented on styles/ranking.css
> +  line-height: 18px;
[こちらのcommitで修正しました](https://github.com/ShunDeveloper/prtimes_htmlcss/pull/11/commits/fcb58173f2866ccdd0813d05b1b3e012edff3923)

2023-05-12 03:09 UTC, ShunDeveloper commented on styles/ranking.css
> +  line-height: 18px;
[こちらのcommitで修正しました](https://github.com/ShunDeveloper/prtimes_htmlcss/pull/11/commits/5e09b8612ec91c670e5dd1374bab4950699666bb)

2023-05-12 03:15 UTC, TepyThai commented on styles/ranking.css
> +  line-height: 1px;
```suggestion
  line-height: 1.5;
```

2023-05-12 03:22 UTC, TepyThai commented on styles/ranking.css
> +  line-height: 1.5px;
```suggestion
  line-height: 1.5;
```

2023-05-12 03:23 UTC, TepyThai approved these changes
LGTM 🚀

2023-05-12 03:23 UTC, merged